version: '3'

services:
  postgres:
    image: postgis/postgis
    env_file: .env
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
#  nestjs:
#    build: .
#    ports:
#      - '3000:3000'
#    depends_on:
#      - postgres
#  pgadmin:
#    image: dpage/pgadmin4
#    restart: unless-stopped
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - '5050:80'
#    depends_on:
#      - postgres
volumes:
  postgres-data:
