version: '3'

services:
  postgres:
    image: postgis/postgis
    env_file: .env
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
#  nestjs:
#    build: .
#    ports:
#      - '3000:3000'
#    depends_on:
#      - postgres
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    user: "${UID}:${GID}"
    restart: unless-stopped
    ports:
      - '5050:80'
    volumes:
      - postgres-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  postgres-data:
