version: '3'

services:
  postgres:
    image: postgis/postgis
    env_file: .env
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - default
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - '5050:80'
    volumes:
      - data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - default
#  nestjs:
#    build: .
#    restart: unless-stopped
#    ports:
#      - '3000:3000'
#    depends_on:
#      - postgres
  ngrok:
    image: wernight/ngrok
    restart: unless-stopped
    volumes:
      - ./ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
    ports:
      - "4040:4040"
    depends_on:
      - postgres
    command: [ "ngrok", "http", "host.docker.internal:3000" ]
    networks:
      - default
volumes:
  data:
networks:
  default: