export type AuthUserPropertyTypes =
    | 'id'
    | 'permissions'
    | 'firstName'
    | 'lastName'
    | 'gender'
    | 'birthDate'
    | 'document'
    | 'documentType'
    | 'email'
    | 'phone'
    | 'password'
    | 'createdAt'
    | 'updatedAt'
    | 'deletedAt'
    | 'createdBy'
    | 'updatedBy'
    | 'deletedBy'
